### ISSUE TITLE
[Feature request] No cursor during dialogue

### ISSUE THREAD

**Issue by bravely-beep** [Vermunds/DialogueMovementEnabler-SE#1]
It'd be cool if the dialogue menu could not show the mouse cursor, but rather have the mouse keep controlling the camera directly just like normal gameplay. This wouldn't affect the dialogue menu controls, as the dialogue options would still be selectable via the mouse wheel and the E key. If this is possible to implement, I think this would be a good complement to the existing features of the mod.

**Comment by Vermunds** [comment]
I'm busy right now and don't have much time for modding, but I'll probably implement this at some point. I even sort of got it working before, there are just some minor issues I'll have to fix.
